### ISSUE TITLE
Close all hack-camp issues

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#498]
![](http://i.imgur.com/dm6iEr5.jpg)

Hack Camp is over! Time to tidy up the place.
/cc @hackedu/hack-camp

**Comment by maxwofford** [comment]
Just 7 issues to go! Let's do this!

**Comment by jonleung** [comment]
Below are all of our remaining tasks and their statuses:
- [x] #520: I will take care of this end of day today
- [x] #517: I am deliberately leaving open because @ad510 is still working on this and it's not time sensitive.
- [x] #494: @zachlatta is taking lead on making sure this is done
- [x] #404: @MaxWofford is taking lead on making sure this gets done (waiting for a pull request from @zachlatta)
- [x] #383: I will make sure this issue is closed by end of day today

/cc @MaxWofford 

EDIT by @maxwofford: Changed name to @ad510

**Comment by maxwofford** [comment]
I'll be gone until September 9th. Assigning to @zachlatta

**Comment by zachlatta** [comment]
Going to go ahead and close this despite #517 not being done because it's waiting on @ad510.

Great work team, we did it. Hack Camp is now over and we've finalized our work from it.

**Comment by jonleung** [comment]
I just merged in @ad510 pull request, we have officially completed all the issues from Hack Camp!

![image](https://cloud.githubusercontent.com/assets/654941/9644770/c4e9db2a-517c-11e5-91d5-bda0519c9534.png)
