### ISSUE TITLE
Hack Camp 2016

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#535]
:raised_hands: 

This issue is to track the organization of Hack Camp 2016. I'll be updating it with more information periodically.

Current todos:
- [x] Set schedule and dates for the program (#536)
- [x] Figure out staffing and financials (#540)
- [x] Set time for weekly staff meetings (#547)
- [x] Create website (#541)
- [x] Public launch (#546)
- [ ] Drive 15 applications by Saturday, May 7th (#575)

**Comment by maxwofford** [comment]
It looks like I'll be taking point on all the issues tracked here. Assigning myself

**Comment by zachlatta** [comment]
:raised_hands:

On Thu, May 5, 2016 at 8:02 AM, Max Wofford notifications@github.com
wrote:

> It looks like I'll be taking point on all the issues tracked here.
> Assigning myself
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/535#issuecomment-217177865

## 

Zach Latta
https://zachlatta.com http://zachlatta.com

**Comment by maxwofford** [comment]
I'll be closing this with #575 instead of updating it with new issues so we can track all of Hack Camp's organization in https://github.com/hackclub/hackcamp/milestones/Organize%20Hack%20Camp%202016

**Comment by maxwofford** [comment]
Closing this issue in favor of #597. Everything tracked in this has been moved over.

**Comment by zachlatta** [comment]
:thumbs_up:

On Fri, May 6, 2016 at 8:08 PM, Max Wofford notifications@github.com
wrote:

> Closed #535 https://github.com/hackclub/hackcamp/issues/535.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hackclub/hackcamp/issues/535#event-653327712

## 

Zach Latta
https://zachlatta.com http://zachlatta.com
