### ISSUE TITLE
Launch Hack Camp marketing

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#546]
Depends on #541 and #543 being done. 

Launch Hack Camp itself.
- [x] Post on Facebook (#552)
  - [x] Hack Club Facebook
  - [x] Other Facebook groups
  - [x] Hackathon Facebook groups (Los Altos Hacks, etc)
- [x] Post on Twitter (#552)
- [x] Send email to community(#551)
- [x] Post to SFUSD (#550)
- [x] Post to blog (hackclub/blog#24)

**Comment by KrishMunot** [comment]
I guess we are done with all the issues listed here. Safe to close this now or do we update our agenda?

**Comment by maxwofford** [comment]
Yep! Thanks @KrishMunot 
![yes](https://cloud.githubusercontent.com/assets/5891442/15046948/6b29aafc-12b0-11e6-89b0-097dc4581383.gif)
