### ISSUE TITLE
Drive 15 criteria applications by 05.07.16

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#575]
Applications are tracked in https://docs.google.com/spreadsheets/d/1HCh5YtN_Y3JXbIMoiUdv-FgYiPZZD1kGg5QnfbsxiCw/edit#gid=149588015

**Comment by maxwofford** [comment]
Current tasks to meet our goal:
- [x] #589 Reach out to SFUSD Principals (@MaxWofford)
- [ ] #577 Send out email on BPN (@MaxWofford)
- [ ] #576 Finalize plan for in-person SFUSD marketing (@ssun098)
- [x] #591 Set up Facebook ads for Hack Camp (@MaxWofford)

**Comment by KrishMunot** [comment]
Do we update the deadline?

**Comment by maxwofford** [comment]
@KrishMunot Thanks for pinging me on this! I'll close this when I open a new issue to track next week's goal

**Comment by maxwofford** [comment]
Actually, updating it now seems like a better plan.

**Comment by maxwofford** [comment]
New goal is at https://github.com/hackclub/hackcamp/issues/602
