### ISSUE TITLE
Organize Hack Camp 2016

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#597]
This issue is to track the status of everything that needs to be prepared for Hack Camp. We'll be regularly updating this issue with progress.
### ~~Week: May 1-7~~
- [x] Figure out staffing and financials for 2016 (#540, @MaxWofford)
- [x] Lock in a time for weekly staff meetings (#547, @MaxWofford)
- [x] Launch Hack Camp marketing (#546, @MaxWofford)
  - [x] Website for 2016 (#541 & #542, @MaxWofford)
  - [x] Post on Facebook (#552, @ssun098)
    - [x] Hack Club Facebook
    - [x] Other Facebook groups
    - [x] Hackathon Facebook groups (Los Altos Hacks, etc)
  - [x] Post on Twitter (#552, @ssun098)
  - [x] Send email to community(#551, @zachlatta)
  - [x] Post to SFUSD (#550, @MaxWofford)
  - [x] Post to blog (hackclub/blog#24, @MaxWofford)
- [ ] Drive 15 qualified applications by Saturday, May 7th (#575, @MaxWofford)
  - [x] Reach out to SFUSD principals (#589, @MaxWofford)
  - [ ] Reach out to SFUSD teachers (#596, @MaxWofford)
  - [ ] Send out email on BPN (#577, @MaxWofford)
  - [x] Set up Facebook ads for Hack Camp (#591, @MaxWofford)
  - [x] Set up Segment analytics with FB (#595, @MaxWofford)
- [ ] Respond to volunteers
### ~~Week: May 8-14~~
- [x] Remake Hack Camp organization issue (#600)
- [ ] Secure a venue (#544, @MaxWofford)
  - [x] 3 venues in talks by Friday (@zachlatta, #610)
- [ ] Drive 25 qualified applications by Saturday, May 14th (#602, @MaxWofford)
  - [x] Reach out to SFUSD CS teachers (#596, @ssun098)
  - [x] Ping SFUSD contacts who haven't responded (#612, @MaxWofford)
  - [ ] Send out email on BPN (#577, @MaxWofford)
  - [x] Create Hack Camp promo codes(#608, @KrishMunot)
  - [x] Send parent-facing blurb to Gemma (#609, @MaxWofford)
- [x] Finalize plan for physical SFUSD marketing (#576, @ssun098)
- [ ] Draft volunteer information blurb (#585, @MaxWofford)
- [ ] Associate Hack Camp with Hack Club (#578, @KrishMunot)
### Week: May 15-21
- [ ] Hack Camp Swags (#581)
  - [ ] Hack Camp t-shirts (#583)
  - [ ] Hack Camp stickers (#580)
- [ ] Reach out to SF libraries (#617, @ssun098)
- [x] Chat with staff members who haven't been in a check-in call (#598, @MaxWofford)
- [ ] Finish first day check list (@MaxWofford)
### Week: May 22-28
- Aiming for 50 qualified signups in total (That's 22 more than we have at time of writing)
  - That's 3 qualified signups per weekday
  - That's 4 of all signups per weekday
- Need venue for first session confirmed
- Need volunteers confirmed
### Week: May 29-June 4

_pending_
## First day checklist
- [ ] 15-20 hackers
- [x] Venue to host event
- [ ] Slide deck for introduction to Hack Camp
- [ ] Energizers
- [ ] Schedule for first day
- [ ] Facilitators (min 2)
- [ ] Curriculum to be run on first day
- [ ] Breakfast

**Comment by maxwofford** [comment]
Nuking this issue and replacing it with #638.
